version: "3.8"

services:
  # Redis service for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: htmlmarkdowner-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Main API application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: htmlmarkdowner-app
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - HOSTNAME=${HOSTNAME:-0.0.0.0}
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://${HOSTNAME:-0.0.0.0}:${PORT:-3000}/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
    driver: local
