version: "3.8"

services:
  # Redis service for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: htmlmarkdowner-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
    driver: local
